### PR TITLE
Update to t3.nano

### PR DESCRIPTION
**Pull request by nitrocode**

### CODE REVIEW

**Comment by sanarena** [comment]
Actually why don't we use nano instead of micro? @nitrocode

**Comment by nitrocode** [comment]
Updated!

**Comment by nitrocode** [comment]
@sanarena could this be merged?

**Comment by sanarena** [comment]
@dumrauf is the master!

**Comment by dumrauf** [comment]
Sorry for the long delay @nitrocode and @sanarena.

So, the main reason for using `t2.micro` in the first place was that - because I'm cheap! And that particular instance type is included in the AWS free tier. Which means that if you spin up the resources in this project in a new AWS account, you get 12 months of your DIY OpenVPN server for free.

I'm not sure if the same can be said for a `t3.nano` instance. However, I see the point around using a cheaper instance type in case you're paying out of pocket.

**Comment by nitrocode** [comment]
Thanks! TIL

>  AWS Free Tier
>
> As part of the AWS Free Tier, you can get started with EC2 for free. This includes 750 hours of Linux and Windows t2.micro instances (t3.micro for the regions in which t2.micro is unavailable), each month for one year. To stay within the Free Tier, use only EC2 Micro instances.

https://aws.amazon.com/ec2/pricing/

**Pull request closed without merging**
